### ISSUE TITLE
Additions to download endpoint to support inline downloads, URL paths

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#105]
The download endpoint should be modified to add support for `content-disposition: inline` headers and to allow downloads (for single files only) via path (e.g. `.../download/DJI_0018.JPG` along with `.../download?path=DJI_0018.JPG`).

These are needed to implement the preview files feature in Hub. 

Check the reference implementation and make sure to test against it? https://github.com/DroneDB/MiniReg/commit/4688116c4104675f119a2e10be6b2ad7388b58b1

**Comment by pierotofy** [comment]
Related: https://github.com/DroneDB/DroneDB/pull/160

**Comment by HeDo88TH** [comment]
All clear!

**Comment by pierotofy** [comment]
You haven't checked MiniReg's implementation. :)

See where it differs.
