### ISSUE TITLE
Cached filesystem loses files with certain naming conventions

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#114]
The issue with naming files with `path-to-file.ext` in the local disk cache is that certain files are at risk of being missed/overriden.

```
[piero:/data/test] $ tree abc
abc
├── 123
│   └── aaa.txt
└── DJI_0018.JPG
```

```
ddb share -r abc abc-123-aaa.txt -s http://192.168.2.251:5000
```

The file at `abc/123/aaa.txt` is lost.

In the absence of using directories, you could prefix paths in the root with a special character.

**Comment by pierotofy** [comment]
Probably a design decision, but for the sake of keeping things simple, shouldn't the `cache` and `ddbstore` path be merged / be the same?

Because we're now storing the `.ddb` (and project folders?) in `ddbstore`, then we reference it in `cache`?

Perhaps could be simplified to keep both `cache` and `ddbstore` in the same place.

I'm assuming the choice to design the cache to use `path-to-file.txt` naming schemes was to facilitate directory creation/traversal?

**Comment by HeDo88TH** [comment]
> The issue with naming files with `path-to-file.ext` in the local disk cache is that certain files are at risk of being missed/overriden.
> 
> ```
> [piero:/data/test] $ tree abc
> abc
> ├── 123
> │   └── aaa.txt
> └── DJI_0018.JPG
> ```
> 
> ```
> ddb share -r abc abc-123-aaa.txt -s http://192.168.2.251:5000
> ```
> 
> The file at `abc/123/aaa.txt` is lost.
> 
> In the absence of using directories, you could prefix paths in the root with a special character.

If i try that command it says

```
ddb share -r abc abc-123-aaa.txt -s http://localhost:25927

Path does not exist: abc-123-aaa.txt
```

If I run 

```
ddb share -r abc abc\123\aaa.txt -s http://localhost:25927
aaa.txt [################################] 100.00% 1.63s
Error response from registry: Entry already uploaded

```

Because ddb is sending duplicate file entries: (the abc gets expanded to aaa.txt)

I'm doing some deeper testing to fix the edge cases

**Comment by HeDo88TH** [comment]
> Probably a design decision, but for the sake of keeping things simple, shouldn't the `cache` and `ddbstore` path be merged / be the same?
> 
> Because we're now storing the `.ddb` (and project folders?) in `ddbstore`, then we reference it in `cache`?
> 
> Perhaps could be simplified to keep both `cache` and `ddbstore` in the same place.
> 
> I'm assuming the choice to design the cache to use `path-to-file.txt` naming schemes was to facilitate directory creation/traversal?

In https://github.com/DroneDB/Registry/pull/115 I switched to a hierarchical tree structure. We can merge the two paths but I don't think that is a good idea. They are managed by two different serviced (`DdbManager` and `ObjectSystem`). It will be a mess because the ddb folder changes as we work on it and it should be synced every time. Plus it is only incidental that we have a local file structure: there could be a different `ObjectSystem` implementation that uses another storage medium, like FTP. For example the basic S3 `ObjectSystem` implementation does not keep anything local.
