### ISSUE TITLE
Query string length could become a problem on download endpoint

### ISSUE THREAD

**Issue by HeDo88TH** [DroneDB/Registry#130]
The length of the query string when calling download endpoint could become a problem. This is exacerbated by the pull mechanism (#129 and https://github.com/DroneDB/DroneDB/pull/195) that requests the new files using this endpoint.
We should probably add a new endpoint that does the same thing but is a POST request instead of GET.

**Comment by pierotofy** [comment]
This is already part (or should be) of the download spec: https://github.com/DroneDB/MiniReg/blob/master/index.js#L81

You can pass multiple `paths` POST parameters to request multiple files.
