### ISSUE TITLE
Cannot push large files

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#138]
Try to add and push a file of ~2.2GB and you will get:

```
[piero:/data/test/test33] $ ddb push
Pushing to 'http://localhost:5000/admin/test33'
Zipping ddb folder
Initializing push
Transfering 'big'
Error response from registry: Failed to read the request form. Request body too large.
```

**Comment by pierotofy** [comment]
Somebody in this thread mentioned that using `in-process hosting` would allow files larger than 2GB to be handled.

https://github.com/dotnet/AspNetCore/issues/2711

http://www.binaryintellect.net/articles/bb086279-ed2a-4628-85f2-7e91125fbe57.aspx

I'm not sure what that entails, but if it solves the file size limitations, it could allow us to solve this AND simplify the share endpoint (we could drop chunked uploads entirely).

**Comment by HeDo88TH** [comment]
> Somebody in this thread mentioned that using `in-process hosting` would allow files larger than 2GB to be handled.
> 
> [dotnet/aspnetcore#2711](https://github.com/dotnet/aspnetcore/issues/2711)
> 
> http://www.binaryintellect.net/articles/bb086279-ed2a-4628-85f2-7e91125fbe57.aspx
> 
> I'm not sure what that entails, but if it solves the file size limitations, it could allow us to solve this AND simplify the share endpoint (we could drop chunked uploads entirely).

In process hosting is only for IIS (windows server). I will investigate further but upload chunking seems the only alternative

**Comment by pierotofy** [comment]
I can't believe this was overlooked, but you simply need to mark your POST endpoints with `[DisableRequestSizeLimit]`.

**Comment by pierotofy** [comment]
Or more safely, `[RequestSizeLimit(long)]`.

**Comment by pierotofy** [comment]
```
ddb push
Pushing to 'http://192.168.2.251:5000/admin/aaa'
Zipping ddb folder
Initializing push
Transfering 'large'
Transfers done
Push complete
```

**Comment by HeDo88TH** [comment]
> ```
> ddb push
> Pushing to 'http://192.168.2.251:5000/admin/aaa'
> Zipping ddb folder
> Initializing push
> Transfering 'large'
> Transfers done
> Push complete
> ```

Nice, I'm working on this.
