### ISSUE TITLE
Cannot push to new dataset

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#139]
If I create a new DroneDB dataset, I cannot push it:

```
mkdir test && cd test
ddb init
touch a.txt
ddb add a.txt
ddb tag http://localhost:5000/admin/test
ddb push
--> Error response from registry: Cannot find dataset
```

Registry should check if a dataset exists, and if not, to initialize an empty one.

**Comment by HeDo88TH** [comment]
I think that it's the intended behaviour. Push command was never drafted like "create if not exists" but only "push to existing dataset". If we need this feature we can add it but it's not a fault 👍

**Comment by pierotofy** [comment]
It's certainly the intended behavior.

**Comment by HeDo88TH** [comment]
My proposal is to add the switch `--create` to the push command. It will perform a share if the dataset does not exist. This way we make the cli smarter and reuse the code already written.

If the user pushes and the dataset does not exist It will advise him to use the `--create` switch

**Comment by pierotofy** [comment]
Mm, I think it should mimic the `docker push` behavior. The user shouldn't need to care if the dataset exists or not. If I push, if the dataset exists, it should be synced, it it doesn't, an empty database should be created. 

I don't think it would be hard would it? It's just a matter of adding the logic:

```
if dataset does not exist:
     create empty dataset

// rest of push logic in registry
```

`share` and `push` serve two different (although similar) purposes.

**Comment by HeDo88TH** [comment]
As stated in **https://docs.docker.com/engine/reference/commandline/push/**

> Use docker image push to share your images to the Docker Hub registry or to a self-hosted one.

It should work as "push or create if not existing", I'll take care of this 👍

**Comment by pierotofy** [comment]
Just don't reuse the `share` logic!

**Comment by HeDo88TH** [comment]
> Just don't reuse the `share` logic!

of course, just create empty dataset
