### ISSUE TITLE
Empty folders do not show up in ddb clone

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#160]
Not sure if this is Registry's fault or ddb's fault. Either way:

 - Share an image to Registry (create dataset)
 - Create a folder

Execute `ddb clone <dataset>`

Witness: the folder does not show up in the cloned folder.

**Comment by HeDo88TH** [comment]
Related to https://github.com/DroneDB/Registry/issues/164 fixed in https://github.com/DroneDB/Registry/pull/159
