### ISSUE TITLE
Renaming a file with an existing path obliterates the file

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#162]
- Upload a file to a dataset (`aaa.txt`)
 - Create a folder `test`
 - Rename the folder to `aaa.txt`.

Witness:
 - Web UI hangs
 - The file has been deleted

Correct behavior:
 - Do not allow renaming if a path exists (show error message).

**Comment by HeDo88TH** [comment]
Fixed in https://github.com/DroneDB/Registry/pull/159
