### ISSUE TITLE
Empty folders are not included in download

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#164]
To reproduce:
 - Create a dataset (upload an image)
 - Create an empty folder (`bbb`)
 - Select the empty folder from the Explorer component (right side) so that the "Download" button on the top right shows `1`.
 - Click `Download`.

Witness:

```
{"error":"Invalid path: 'bbb'"}
```

**Comment by HeDo88TH** [comment]
Fixed in https://github.com/DroneDB/Registry/pull/159
