### ISSUE TITLE
Onboarding process

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#2]
After starting a brand new instance of the registry, the home page http://localhost:5000 should display some sort of welcome message and direct users to the next steps.

Perhaps the first step would be to setup a password for the "admin" account.

Other future steps (not required right away) could involve choosing the storage configuration, branding, name of registry, etc.

**Comment by HeDo88TH** [comment]
The DroneDB.Registry.Web is only the WebAPI server. I will expose several endpoints to manage users and to edit internal settings. The initial settings will be loaded from the appsettings.json file.

**Comment by pierotofy** [comment]
Ok, user management forms can be decoupled. We should still have a splash screen if a user runs this and opens http://localhost:5000 (for example, a "registry is running!" or some other info. Think 
![image](https://user-images.githubusercontent.com/1951843/87159291-1d8b4600-c28f-11ea-9081-b18fd55fdc2c.png)
