### ISSUE TITLE
Decouple Tiler from Registry or Horizontally Scale

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#211]
It should be possible to run the tiler (a subset of the Registry API) on a separate server or process so that all requests to do dynamic tiling (or other CPU intensive operations for the matter) do not impact the performance of the rest of the application.

Hub could then forward requests to a different subdomain (tiles.dronedb.app) to process tile requests for example.

**Comment by HeDo88TH** [comment]
Partially addressed by out-of-process workers. It's on the roadmap to move all the computing outside the webserver process.
