### ISSUE TITLE
Bring native bindings into Registry

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#219]
While having a separate nuget package for bindings might seem like a clever choice, it actually hinders development efforts by needing to maintain two separate interfaces (the bindings themselves, plus the adapters/ports in registry).

Just take a look at the adapters code in Registry; it duplicates a lot of model definitions.

We have no known users of the nuget package.

We should make the design easier.

**Comment by HeDo88TH** [comment]
I do agree with your points. It's on my list!
