### ISSUE TITLE
/orgs/admin/ds returns wrong or duplicate information

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#230]
```
{
  "id": 12,
  "slug": "5ad1ayhjvpsflksv",
  "name": "5ad1ayhjvpsflksv",
  "creationDate": "2021-12-29T10:49:09.9710471",
  "objectsCount": 0,
  "lastEdit": null,
  "properties": {
    "entries": 2,
    "meta": {
      "name": {
        "data": "Brighton Beach",
        "id": "6a5c7db7-e00c-431d-b7a8-86e0d862ad2c",
        "mtime": 1640797543
      }
    },
    "public": true
  },
  "isPublic": true,
  "size": 7956545
}
```

 * objectsCount is wrong and redundant (entries)
 * lastEdit is wrong (and not needed)
 * isPublic is redundant
 * name is redundant (superseded by meta)

**Comment by HeDo88TH** [comment]
I agree that all these properties can be removed but does this affect Hub?

**Comment by pierotofy** [comment]
I don't think these affect hub.

**Comment by HeDo88TH** [comment]
> I don't think these affect hub.
> 
> I think the `EntryAttributes` wrapper can probably be removed/simplified.

Hub dataset rename is broken, I will fix it.
We should remove the `Name` column from the registry database too.

**Comment by pierotofy** [comment]
How is it broken?
