### ISSUE TITLE
Add rollback to share endpoints

### ISSUE THREAD

**Issue by HeDo88TH** [DroneDB/Registry#235]
We should add a new `rollback` (or `cancel`) endpoint to cancel a share session. This way Registry can perform the cleanup actions required to get rid of the partially uploaded files.

**Comment by pierotofy** [comment]
This will not work (well); it relies on the client communicating that a share session is being terminated. This does not always happen (e.g. internet disconnection).

Better to have a background task checking for "stale" sessions.

This is the approach I implemented in ClusterODM. It works well.

**Comment by HeDo88TH** [comment]
> This will not work (well); it relies on the client communicating that a share session is being terminated. This does not always happen (e.g. internet disconnection).
> 
> Better to have a background task checking for "stale" sessions.
> 
> This is the approach I implemented in ClusterODM. It works well.

Yes indeed, but having both the mechanisms in place allows to clean up early and leave less junk around for less time.

**Comment by HeDo88TH** [comment]
Closed by #236
