### ISSUE TITLE
unable to access settings and status page in docker/production

### ISSUE THREAD

**Issue by borsti67** [DroneDB/Registry#246]
Hello, 
following the readme, on a Ubuntu 20.04 LTS (server) VM I have 
- cloned the repository and updated the submodules
- installed the latest docker (Docker version 20.10.12, build e91ed57)
- installed the latest docker-compose (docker-compose version 1.29.2, build 5becea4c)
- created a `.env` with own passwords etc
- executed run.sh after `chmod +x`

I can access `<IP>:5000` and login with my credentials.
Status of the containers looks good:
```
production_db_1           docker-entrypoint.sh mariadbd    Up (healthy)   3306/tcp
production_phpmyadmin_1   /docker-entrypoint.sh apac ...   Up             0.0.0.0:8080->80/tcp,:::8080->80/tcp
production_registry_1     /bin/sh -c dotnet Registry ...   Up             0.0.0.0:5000->5000/tcp,:::5000->5000/tcp
```
When I push the `settings` button nothing happens at all.
`docker-compose logs -f` does not report anything at this point. There is only one startup error reported, where I'm not sure if it is related:
```
registry_1    | [17:23:50 ERR] Index was outside the bounds of the array.
registry_1    | System.IndexOutOfRangeException: Index was outside the bounds of the array.
registry_1    |    at Hangfire.MySql.MySqlStorage.<>c.<ToString>b__14_1(String[] x)
registry_1    |    at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
registry_1    |    at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
registry_1    |    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
registry_1    |    at Hangfire.MySql.MySqlStorage.ToString()
registry_1    | [17:23:51 WRN] The property 'User.Metadata' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
registry_1    |  -> Application startup
registry_1    |  ?> Environment: Production
registry_1    |  ?> Version: 1.0.6.0
registry_1    |  ?> Application started at 02/25/2022 17:23:52
registry_1    |  ?> Now listening on: http://0.0.0.0:5000
```

`<IP>:5000/status` also only displays a blank page.

What am I missing?

As a sidenote: the "healthcheck" generates an error message every 30 sec, I would recommend to change in `docker-compose.yml` like so:
```
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$MYSQL_ROOT_PASSWORD"]
```

**Comment by borsti67** [comment]
Quick update from today:

- /status now states an invalid URL and asks if I want to report it here
- the config button is only visible within a dataset where I can set visibility to private and create license/readme files. 

Is it correct there is no admin config page where I could create users?

**Comment by HeDo88TH** [comment]
> Quick update from today:
> 
> * /status now states an invalid URL and asks if I want to report it here
> * the config button is only visible within a dataset where I can set visibility to private and create license/readme files.
> 
> Is it correct there is no admin config page where I could create users?

Thanks for your feedback. The actual "status" url is [/quickhealth](http://localhost:5000/quickhealth) (or [/health](http://localhost:5000/health)) https://github.com/DroneDB/Registry/blob/ba1b2e6aa716375738dca89aaf8dcc9b570849c2/Registry.Web/Startup.cs#L337

In #253 I corrected the readme. Plus I added your suggestion to our docker-compose health check.

Don't hesistate to give further feedback!

**Comment by pierotofy** [comment]
> Is it correct there is no admin config page where I could create users? 

Currently not, but it's on the roadmap. https://github.com/DroneDB/DroneDB#roadmap (we'd welcome contributions too!)
