### ISSUE TITLE
Tons of failed requests to access database

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#256]
A service in Registry continues to attempt to log to the DB (unsuccessfully):

```
db_1          | 2022-03-27 17:11:24 97 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
```

I think it's the monitor service.

**Comment by HeDo88TH** [comment]
I thought this was fixed in https://github.com/DroneDB/Registry/pull/253/commits/9b99f855cc2298882a9c43742bd0e44de6202bc7
Maybe we just forgot to update our docker compose file 🤔

**Comment by pierotofy** [comment]
That was it.
