### ISSUE TITLE
Add STAC catalog generation

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#261]
We should offer endpoints to access/generate STAC catalog items: https://stacspec.org/

It should be feasible, as we already have most of the information available in DroneDB.

**Comment by AsgerPetersen** [comment]
When you implement this please allow me to draw you attention to the STAC metadata extension [perspective-imagery](https://github.com/stac-extensions/perspective-imagery) it allows to specify photogrammetric metadata for each image. So I think it would be a perfect fit for this use case.
