### ISSUE TITLE
problem with server?  502 bad gateway?

### ISSUE THREAD

**Issue by holoboss** [DroneDB/Registry#265]
Hello, I am trying over and over to access the Hub, to upload and work on some files - but i get 502 Bad Gateway error. and when i go to dashboard it shows I have 0 files on server (while couple ago it was all ok, and showed about 1.6 GB of files.
Not sure if admins are aware and if it is for all users, or just me for some reason...
Thank you!

**Comment by HeDo88TH** [comment]
We are working on it. It will come back online as soon as possible

**Comment by HeDo88TH** [comment]
It is back online now 🚀

**Comment by holoboss** [comment]
fantastic! Thank you!
