### ISSUE TITLE
Deleting Folder: Error: Path 'Test' not found in dataset

### ISSUE THREAD

**Issue by JustinBack** [DroneDB/Registry#268]
I just setup DroneDB using the production instructions in the docs but every time I try to delete a directory the error "Error: Path 'XXXXX' not found in dataset.

```
production-registry-1  | [22:52:17 ERR] Exception in Objects controller Delete('org-test', 'dataset-test', 'Test')
production-registry-1  | Registry.Web.Exceptions.BadRequestException: Path 'Test' not found in dataset
production-registry-1  |    at Registry.Web.Services.Managers.ObjectsManager.Delete(String orgSlug, String dsSlug, String path) in /R
egistry/Registry.Web/Services/Managers/ObjectsManager.cs:line 334
production-registry-1  |    at Registry.Web.Controllers.ObjectsController.Delete(String orgSlug, String dsSlug, String path) in /Regi
stry/Registry.Web/Controllers/ObjectsController.cs:line 325
```

The Hub shows the folder
<img width="489" alt="Bildschirmfoto 2022-05-26 um 00 54 11" src="https://user-images.githubusercontent.com/40178814/170382617-b5ba5e7a-c48e-4c2e-9176-216dce4ba694.png">

I cannot get the Registry reliably to run.

I can confirm that the "Test" folder exists on the drive, no SQL errors or anything, just the error above.

**Comment by JustinBack** [comment]
Note: I am running on the master branch as there is no release

**Comment by JustinBack** [comment]
Just tested two cases.

If the folder is created in the Hub without any files. It is NOT created on disk. The Hub shows the folder though

If the folder is created, then a file uploaded I can delete the folder.

**Comment by HeDo88TH** [comment]
Thanks for your feedback. @pierotofy changed the login of the list command [here](https://github.com/DroneDB/DroneDB/commit/c16edae75813a81ae6e4bb119c20096336b474c4) and [here](https://github.com/DroneDB/DroneDB/commit/73dea22b0b8e776898b9c9a547a9c3ad20a45d92). I am currently updating the Registry logic to account for the changes. Great PR incoming that will bring many improvements both in usability and reliability

**Comment by JustinBack** [comment]
Can confirm it works! Thanks a lot :-)
