### ISSUE TITLE
Unable to create public datasets

### ISSUE THREAD

**Issue by Karageek** [DroneDB/Registry#284]
Since latest update that added imperial measurements, I have been unable to set any public datasets. Either create or change existing. when I create a dataset and set it public it says public but immediately changes to private. Any existing datasets exhibit the same behavior. Same goes for unlisted it changes it to private. I've created new organizations and all have same issue.
Organizations are able to be set to public but not the actual datasets. Both empty or datasets with items.

**Comment by HeDo88TH** [comment]
We know about this issue. We are working on it, I'll keep you posted.
