### ISSUE TITLE
Private Folder: Acces files / API without logging in

### ISSUE THREAD

**Issue by MarkAtGit** [DroneDB/Registry#299]
Hi, first of all my compliments to DroneDB Registry. Im just getting started with the application / API and it looks very promising. When working with the share / API function one issue "caught" my eye. Since I can also duplicate this one hub.dronedb.app I'm using this as an example.

1) I created a private dataset on hub.dronedb.app
2) In this private dataset I created 4 subfolders (which contents should be private as well, right?)
3) In subfolder 1 I uploaded an image.
4) I made a share link from the image from subfolder 1 I would like to share to a friend: https://hub.dronedb.app/orgs/aeret/ds/private_set_1/download/very_private1/flower.jpeg?inline=1

5) Because I now know the name of the hidden dataset **private_set_1** I can request all the subfolders in this dataset via the /list command

https://hub.dronedb.app/orgs/aeret/ds/private_set_1/list

6) which gives me 4 subfolders

very_private1
very_private2
very_private3
very_private4

7) with the /list?path= command I can see the files in each private subfolder, for example:
https://hub.dronedb.app/orgs/aeret/ds/private_set_1/list?path=very_private4 

8) This gives me the content of this folder, such as "path":"very_private4/very_secret_picture.jpg"

9) It's possible to download this file also with a small change in the url from step 4

https://hub.dronedb.app/orgs/aeret/ds/private_set_1/download/very_private4/very_secret_picture.jpg?inline=1

### Summary
When I try to acces the API via https://hub.dronedb.app/orgs/aeret/ it gives me a warning when a user is not logged in.

When I know the name of a (private) folder I can acces the contents without logging in (step 5 to 9)
https://hub.dronedb.app/orgs/aeret/ds/private_set_1/list

small edit: 

The reason I'm posting this issue is that on my own DroneDB Registry installation I have a private dataset with 50 subfolders (11000 images and 100GB). I don't like the idea that when sharing one image from this private set, one can see / view all the contects of these subfolders via the above workflow.

**Comment by HeDo88TH** [comment]
Sorry for the late reply. You set the dataset as `unlisted` not `private`. This is the expected behaviour.
If you share a link in a private dataset, the dataset becomes unlisted, otherwise no files can be viewed from other users.

We are working on a new authorization infrastructure with a GUI, as cited in our roadmap: https://dronedb.app/new-dronedb-roadmap/

Thanks for the feedback
