### ISSUE TITLE
Seeking Method to Remove Folder from Index via API, Similar to remove in ddb CLI

### ISSUE THREAD

**Issue by lupionpe** [DroneDB/Registry#302]
Hello Team,

I'm in a bit of a puzzle and need your expertise. Here's my goal:

**Objective:** I want to remove a folder from the index using the API. The catch is, I need to do this without deleting the folder's content and ensuring it remains inaccessible.
I've already taken a peek at ddb CLI documentation and noticed the [`remove`](https://docs.dronedb.app/docs/cli#remove) command seems to do just what I need. However, I'm looking for a way to achieve this through our API.

**Question:** Is there an API endpoint that offers functionality similar to the remove command in the ddb CLI?

I did try to find answers in the Swagger documentation, but it seems a bit unclear on this specific functionality.

Any guidance or pointers would be greatly appreciated!
Thank you!

**Comment by HeDo88TH** [comment]
Sorry for the late reply. I do not understand what you mean when you say "remove a folder without deleting the folder's content and ensuring it remains inaccessible"

Can you reformulate it please?
