### ISSUE TITLE
Use .NET bindings instead of system calls to ddb exe

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#37]
We should use the .NET bindings library instead of invoking the ddb executable.

**Comment by HeDo88TH** [comment]
This is now the top 1 priority

**Comment by pierotofy** [comment]
ETA on this?

**Comment by HeDo88TH** [comment]
ETA is when we successfully merge https://github.com/DroneDB/DroneDB/pull/83 and add the list command. Then, after we update the bindings with the new functions we can back to work on this.
