### ISSUE TITLE
Calling /ddb/share/init twice returns error

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#40]
Invoking:

`POST /ddb/share/init`

With the same `tag` parameter twice returns:

```
{
 "error": "Value cannot be null. (Parameter 'source')"
}
```

This could occur if a user starts the sharing process, but the connection is interrupted, or needs to be restarted.

**Comment by pierotofy** [comment]
This is partially resolved, the fix in #42 doesn't address the main concern: what happens if my connection is interrupted?

As an API client, I need to be able to restart the upload process somehow.

With:

```
{
    "error": "Cannot start a new batch if there are others already running"
}
```

I'm stuck.

**Comment by HeDo88TH** [comment]
The present case is when it is called `init ` but the connection is interrupted and the client is unable to obtain the token. At that point he calls `init` again but replies that there is already a batch running.
This is an architectural decision. It is not possible to run multiple batches simultaneously on the same dataset. It is already possible to call the `batches` endpoint on the dataset to enumerate the batches in progress or concluded and recover the token that has not arrived. A batch has not been committed if the `end` field is `null`.

**Comment by pierotofy** [comment]
Then let's change the architecture, because it currently leaves the burden of logic onto the client:

 - I can't just call /ddb/share/init, because I need to first check the `batches` endpoint if there are any existing batches.
 - If I press CTRL+C (or cancel) an upload, because I realize that there's a mistake (perhaps I uploaded a file that I didn't want to share), then I'm stuck, there's no way for me to re-do the upload and omit the files I didn't want to include.

The point of having a "share" endpoint is so that a client doesn't need to know about other endpoints. It should just "work".

Look at it from the point of view of the `ddb share` command.
