### ISSUE TITLE
API semantics

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#48]
Just looking at the API, I was wondering if we should change one thing, namely the `ddb` prefix.

`GET /ddb` returns the list of organizations. Wouldn't this be better called `GET /orgs`?

`POST /ddb/share/init`, `POST /ddb/share/upload/` and `POST /ddb/share/commit` could then also be abbreviated `/share/init`, `/share/upload`/ and `/share/commit/` since they are just helpers.

I can take care of doing this if needed.

**Comment by HeDo88TH** [comment]
It's definitely more coherent
