### ISSUE TITLE
Add support for form-data

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#5]
Currently unsupported, but probably should?

![image](https://user-images.githubusercontent.com/1951843/87071210-e4e46180-c1e7-11ea-88bd-2703f3d8942d.png)

Both modes (JSON and form-data should be supported).

**Comment by HeDo88TH** [comment]
There is no straightforward way of implementing it. We can re-open this issue if this feature is explicitly requested.

**Comment by HeDo88TH** [comment]
This can be implemented: https://stackoverflow.com/questions/57515863/how-to-support-both-json-and-urlencoded-content-types-in-web-api
