### ISSUE TITLE
Add /orgs/{org}/ds/{ds}/list endpoint

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#68]
Chunked uploads take priority at the moment, but this should be worked on afterwards.

`POST /orgs/:org/ds/:ds/list`

Takes a single, optional formData `path` parameter that limits the scope of the listing to a specific directory. (Default: show the root without recursion, depth 1), same as `ddb ls <path>`.

See MiniReg's implementation for details: https://github.com/DroneDB/MiniReg/blob/master/libs/list.js#L6

**Comment by HeDo88TH** [comment]
It already exists on registry:

`POST /orgs/:org/ds/:ds/info
`

**Comment by pierotofy** [comment]
Ah, great! Can we simply rename it then?

Also does it support a `path` parameter for restricting the listing to a particular path in the tree?
