### ISSUE TITLE
[Stress Test] - Test 20 multiple concurrent uploads of 100s of small files

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#72]
Test that Registry is able to handle gracefully concurrent uploads (20?) of 100s of small files (empty .txt files, or .txt files with small content, plus some images) without crashing.

**Comment by HeDo88TH** [comment]
I will setup a Gatling simulation (https://gatling.io/docs/current/) to stress test Registry. We can evaluate performances and spot early race conditions

**Comment by HeDo88TH** [comment]
It is now possible to test the API with heavy load by using https://github.com/DroneDB/StressTester

**Comment by pierotofy** [comment]
Interesting results. (Looking at https://digipa.it/wp-content/uploads/sharetest-20210122180119645/index.html) 

It seems to suggest that there's some bottleneck, as `upload_8` took on average `20831 msecs` (that's 20 seconds!).

**Comment by pierotofy** [comment]
Results from MiniReg (on Linux):

[sharetest-minireg-linux-20210125191541046.zip](https://github.com/DroneDB/Registry/files/5869115/sharetest-minireg-linux-20210125191541046.zip)

Mean upload: `143ms`

**Comment by pierotofy** [comment]
![image](https://user-images.githubusercontent.com/1951843/105755116-dd34a200-5f18-11eb-9bcf-31f266f7e5ae.png)
