### ISSUE TITLE
Add support for reading JWT token from cookies

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#75]
It should be possible to authenticate the JWT token via cookies as an alternative to using the Authorization header.

Cookie name: `jwtToken`

This is needed for accessing `GET` URLs directly from a web browser (e.g. download links).

Registry does not need to send the cookie itself at this moment. (It's set on the client app).

**Comment by HeDo88TH** [comment]
Can't you simply use

`curl -H 'Accept: application/json' -H "Authorization: Bearer ${TOKEN}" https://{hostname}/api/myresource`

What's the point of the cookie?

**Comment by pierotofy** [comment]
If I have a link to download dataset files:

`http://hostname/orgs/admin/ds/test123/download`

I want to be able to take that link and share it.

But sometimes the link can only be accessed by somebody who's logged in.

If you don't have a cookie, you can't verify access authorization.

See #76
